services:
  server:
    build: .
    container_name: kosmo-server
    entrypoint: ["/bin/sh", "-c"]
    command: "cd /root && /usr/local/bin/kosmo setup && KOSMO_DAEMON=1 /usr/local/bin/kosmo start --port 8080"
    ports:
      - "8080:8080"
    volumes:
      - server-keys:/root/.kosmo
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 5s

  client:
    build: .
    container_name: kosmo-client
    entrypoint: ["/bin/sh", "-c"]
    command: |
      sleep 10
      cd /app
      chmod +x test.sh
      ./test.sh
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./sample:/app/sample
      - ./test.sh:/app/test.sh
      - server-keys:/root/.kosmo
    environment:
      - SERVER_HOST=server

volumes:
  server-keys:

